version: "3.0"

services:
  resource-service-app:
    image: resource-service-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resource-service-app-microservices_course
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      AWS_S3_ENDPOINTURL: ${AWS_S3_URL}
      AWS_S3_BACKETNAME: ${AWS_S3_BUCKET}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    expose:
      - "8080:8080"
    depends_on:
      - localstack
      - rabbitmq
      - postgres
    networks:
      - service-registry_default
      - postgres
      - localstack
      - rabbitmq

  localstack:
    container_name: localstack_microservices_course
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,s3
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=4566
    ports:
      - '4566:4566'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

  rabbitmq:
    container_name: rabbit_microservices_course
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq

  postgres:
    container_name: postgres_resource_service_microservices_course
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - postgres

networks:
  postgres:
  localstack:
  rabbitmq:
  service-registry_default:
    external: true
