version: "3.0"

services:
  localstack:
    container_name: localstack_microservices_course
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda,s3
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EDGE_PORT=4566
    ports:
      - '4566:4566'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  rabbitmq:
    container_name: rabbit_microservices_course
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    container_name: postgres_resource_service_microservices_course
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resource
    ports:
      - '5432:5432'
