apiVersion: v1
kind: Service
metadata:
  name: resource-postgres
  namespace: k8s-program
spec:
  selector:
    app: resource-postgres
  ports:
    - port: 5433
      targetPort: 5432
  type: ClusterIP