apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-postgres
  namespace: k8s-program
  labels:
    app: resource-postgres
spec:
  serviceName: resource-postgres
  replicas: 1
  selector:
    matchLabels:
      app: resource-postgres
  template:
    metadata:
      name: resource-postgres
      labels:
        app: resource-postgres
    spec:
      containers:
        - name: resource-postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: resource-postgres
          envFrom:
            - configMapRef:
                name: resource-postgres-config
      volumes:
        - name: resource-postgres
          persistentVolumeClaim:
            claimName: postgres-resource-volume-claim
      restartPolicy: Always
