spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/resource
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: resource-ids
          group: resource-processor
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 5000ms
        max-attempts: 2

aws:
  s3:
    endpoint-url: http://localhost:4566
    bucket-name: resources
    region: us-east-1

logging:
  level:
    root: info
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
  config: classpath:logback-spring-local.xml

server:
  tomcat:
    max-swallow-size: 20MB
    max-http-form-post-size: 20MB
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

services:
  url:
    song-service: http://localhost:8081/api/v1/songs

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      storage-service-circuit-breaker:
        register-health-indicator: true
        minimum-number-of-calls: 2
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 2m
        permitted-number-of-calls-in-half-open-state: 1
        sliding-window-size: 2
        sliding-window-type: count_based
  retry:
    retry-aspect-order: 2
    instances:
      storage-service-retry:
        max-attempts: 2
        wait-duration: 5s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

management:
  health:
    circuitbreakers:
      enabled: true
    retries:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
