spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://localhost:5432/resource
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: resource-ids
          group: resource-processor
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 5000ms
        max-attempts: 2

aws:
  s3:
    endpoint-url: http://localhost:4566
    bucket-name: resources
    region: us-east-1

logging:
  level:
    root: info
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

server:
  tomcat:
    max-swallow-size: 20MB
    max-http-form-post-size: 20MB
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

services:
  url:
    song-service: http://localhost:8081/api/v1/songs

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic