apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource
  namespace: k8s-program
  labels:
    app: resource
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource
  template:
    metadata:
      name: resource
      labels:
        app: resource
    spec:
      containers:
        - name: resource
          image: resource:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://resource-postgres:5433/resource
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: AWS_S3_ENDPOINTURL
              value: http://localstack:4566
            - name: AWS_S3_BACKETNAME
              value: resources
      restartPolicy: Always
