apiVersion: v1
kind: Service
metadata:
  name: resource
  namespace: k8s-program
spec:
  selector:
    app: resource
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30002
  type: NodePort