apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: k8s-program
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
  type: ClusterIP