apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: localstack
  namespace: k8s-program
  labels:
    app: localstack
spec:
  serviceName: localstack
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      name: localstack
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICES
              value: "lambda,s3"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: DOCKER_HOST
              value: "unix:///var/run/docker.sock"
            - name: EDGE_PORT
              value: "4566"
          ports:
            - containerPort: 4566
      restartPolicy: Always
